### PR TITLE
Fix cat and find message pluralization

### LINKED ISSUE #149: Cat displays "1 persons listed"
Person is plural even though only 1 person listed
(I know it's insignificant but I don't like seeing it, I'll handle the issue)

### PR DESCRIPTION
**Pull request by Cleaach**
## Description

Fix pluralization after performing a cat/find command

## Related Issue

Closes #149 

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] Documentation update
- [ ] Code refactoring
- [ ] Test addition/modification

## Testing Done

- [ ] All existing tests pass
- [x] Added new tests for the changes
- [x] Manual testing performed

## Checklist

- [x] My code follows the project's code style guidelines
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -15,10 +15,16 @@ public class Messages {
...
     public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The person index provided is invalid";
-    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
     public static final String MESSAGE_DUPLICATE_FIELDS =
                 "Multiple values specified for the following single-valued field(s): ";
 
+    /**
+     * Returns a message indicating the number of persons listed with correct pluralization.
+     */
+    public static String getPersonsListedMessage(int count) {
+        return count == 1 ? "1 person listed!" : String.format("%d persons listed!", count);
```
Comment (javierlimt6) [inline src/main/java/seedu/address/logic/Messages.java]: why not use people instead of persons then :)

**Review by javierlimt6 — CHANGES_REQUESTED** [review]
